# Generated by Django 5.0 on 2024-03-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='tutor_id',
        ),
    ]
